### ISSUE TITLE
Can I use nested element selectors according to this method?

### ISSUE THREAD

**Issue by justusromijn** [bem/bem-method#110]
In a project where we would like to use the bem-methology, I have a situation where there are some nested elements within a block.

I have the following code sample:
```
<li class="newsitem newsitem--unread">
	<h4 class="newsitem__date">Yesterday</h4>
	<section class="newsitem__content">

			<section class="newsitem__sender">
				<img class="newsitem__sender__thumbnail" src="some-source.png" title="Mr. Foo" />
				<p class="newsitem__sender__message">Foo likes bar, as does baz.</p>
			</section>

		<h3 class="newsitem__title">Some news item.</h3>
		<p class="newsitem__summary">Blablabla...</p>
	</section>
</li>
```

Is it okay to use selectors like `newsitem__sender__thumbnail` and `newsitem__sender__message`, or is there another way? I'm not able to find any documentation on these scenarios. This newsitem__sender part is not a block of it's own, its just a part of a newsitem block.

**Comment by tadatuta** [comment]
https://en.bem.info/methodology/faq/#why-does-bem-not-recommend-using-elements-within-elements-block__elem1__elem2
