### ISSUE TITLE
Feedback for "Организация файловой системы"

### ISSUE THREAD

**Issue by lasdolphin** [bem/bem-method#190]
<code>Модификатору соответствует поддиректория в директории блока
Имя директории соответствует имени модификатора
Техническая реализация модификатора размещается в файлах в этой директории
Названия файлов содержат как имя, так и значение модификатора
Этот вариант позволяет наглядно просматривать структуру блока в файловой системе

Мне кажется что исходя из приведенного примера "модификатору соответствует поддиректория в директории элемента" а не блока.
Спасибо.

**Comment by gela-d** [comment]
@lasdolphin эта статья обновилась недавно https://ru.bem.info/method/filesystem/
Описание стало удобней и прозрачней?
