### ISSUE TITLE
Feedback for "Создаем свой проект на БЭМ"

### ISSUE THREAD

**Issue by massachusetts2** [bem/bem-method#208]
в строке "Пример кода head.deps.js.  "  ошибка. файл goods.deps.js

**Comment by tadatuta** [comment]
Исправлено в
https://github.com/bem/bem-method/commit/660268aedfb4f8f7e38338d360c8c749364d4914
https://github.com/bem/bem-method/commit/6545ae5e9043fc40eb545b1515ae43b20888778c

@massachusetts2 Спасибо!
