### ISSUE TITLE
Feedback for "Создаем свой проект на БЭМ"

### ISSUE THREAD

**Issue by massachusetts2** [bem/bem-method#209]
раздел "Миксы блоков и элементов". подключается библиотека "j", для отображения элемента box. в какой момент и как должен подключаться файл стилей для элемента box?

тот же вопрос и про файл js библиотеки

**Comment by tadatuta** [comment]
@dab Дима, помоги с ответом, пожалуйста

**Comment by gela-d** [comment]
@massachusetts2 Актуально еще?

**Comment by massachusetts2** [comment]
да

**Comment by gela-d** [comment]
По зависимостям, все файлы по технологиям, которые нужны для страницы, приезжают во время сборки общего бандла. Так что, отдельно их подключать не нужно.

**Comment by gela-d** [comment]
Вот тут еще подробнее описан процесс https://ru.bem.info/forum/352/#comment-89579575
