### ISSUE TITLE
We need strong definitions for methodology

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-method#212]
Ref: https://ru.bem.info/forum/issues/185/

Can we go a scientific way and strongly define terms?

E.g. I can make a PR with fixes for russian version, then we talk and apply them, and then translate to english and other languages. Thoughts?

/cc @vithar @tadatuta @veged @narqo

**Comment by tadatuta** [comment]
cc @innabelaya

**Comment by gela-d** [comment]
@innabelaya Инна, Вовын февральский сс потерялся видимо :)

**Comment by tadatuta** [comment]
Partially done in Russian here https://ru.bem.info/method/definitions/
Translation is in progress.

**Comment by zxqfox** [comment]
<3 !!!
