### ISSUE TITLE
Feedback for "Собираем статическую страницу на БЭМ"

### ISSUE THREAD

**Issue by dpantele** [bem/bem-method#213]
1. Не указан в инструкциях bower install, без него не создаётся libs и получается вот такая ошибка при первом запуске сервера:
```
Error: ENOENT, no such file or directory '/data/start-project/libs/bem-core/common.blocks'
   at Object.fs.readdirSync (fs.js:666:18)
   at module.exports.inherit.load (/data/start-project/node_modules/enb-bem-techs/lib/levels/level.js:212:28)
   at /data/start-project/node_modules/enb-bem-techs/techs/levels.js:126:38
   at Array.map (native)
   at /data/start-project/node_modules/enb-bem-techs/techs/levels.js:125:42
   at Array.0 (/data/start-project/node_modules/enb/node_modules/vow/lib/vow.js:202:56)
   at Object.callFns [as _onImmediate] (/data/start-project/node_modules/enb/node_modules/vow/lib/vow.js:462:35)
   at processImmediate [as _immediateCallback] (timers.js:354:15)
```

2. prose.io не работает - просто ничего не загружается по указанной ссылке

**Comment by tadatuta** [comment]
@dpantele `bower install` должен автоматически запуститься на npm postinstall (см. https://github.com/bem/project-stub/blob/bem-core/package.json#L35)

Предположу, что это из-за установки из-под `root`?
`bower` по умолчанию не ставит свои зависимости под `root`.

**Comment by dpantele** [comment]
Да, телепатия отличная, действительно из-за рута.

А можно как-то сделать поведение bower-npm-install аналогичным поведению bower install без --allow-root, то есть ругаться и писать понятное сообщение? Или это сюда: https://github.com/arikon/bower-npm-install ?

**Comment by tadatuta** [comment]
он и сейчас ругается в виде
```
npm WARN cannot run in wd bem-project-stub@1.0.0 bower-npm-install (wd=/Users/tadatuta/Sites/pr-stub-update)
```
но в целом да, было бы неплохо писать что-то более внятное.
