### ISSUE TITLE
Чекаутить тег вместо хеша в "Собираем статическую страницу на БЭМ"

### ISSUE THREAD

**Issue by h4** [bem/bem-method#216]
Предлагаю заменить 

```
git clone https://github.com/bem/project-stub.git start-project
cd start-project
git checkout 13ae0e18ef8f48bc552b4944f7e5971c5b5f4768
npm install
```

на 
```
git clone https://github.com/bem/project-stub.git start-project
cd start-project
git checkout quick-start-static-v1
npm install
```

То есть создать тег в `project-stub.git` и чекаутить его. Переключаться на хеш коммита — слишком хардкорно даже для меня, а уж для первого шага в «Быстром старте» — совсем издевательство.

**Comment by innabelaya** [comment]
@h4 Миша, спасибо! Заменили немного по-другому в рамках https://github.com/bem/bem-method/pull/214. Вот так `git clone https://github.com/bem/project-stub.git --depth 1 --branch v1.0.0 test-project`

**Comment by h4** [comment]
@innabelaya так даже лучше.
