### ISSUE TITLE
Битая ссылка на редактирование в prose.io

### ISSUE THREAD

**Issue by h4** [bem/bem-method#217]
1. Захожу на https://ru.bem.info/tutorials/quick-start-static/
1. Нажимаю «...или поправить статью с помощью prose.io.»
1. Попадаю на prose.io/#bem/bem-method/edit/**null**/articles/quick-start-static/quick-start-static.ru.md
1. Ничего не работает

**Comment by tadatuta** [comment]
@h4 Привет!
Проблема в том, что часть текстов попадает не из веток, а из тегов и тогда непонятно, куда коммитить исправление. Мы про это знаем, но пока все никак не доберемся починить :(

// cc @gela-d @tormozz48 
Давайте, может, пока вообще оторвем ссылку на prose.io, если страница собрана из тега? Получится сделать малой кровью?

**Comment by gela-d** [comment]
@h4 Миша, а можешь сейчас еще раз проверить кейс?
Может быть, это на самом сайте были проблемы, мы вчера перевыкатывали код и сейчас у меня все для редактирования хорошо открывается.

**Comment by h4** [comment]
@gela-d сейчас всё ОК.

**Comment by gela-d** [comment]
@tadatuta А на страницах из тегов все работает вроде бы "относительно" правильно - https://ru.bem.info/technology/bemhtml/2.3.0/intro/
Здесь, конечно, противоречивый момент в том, что человек хочет поправить статью в конкретном теге, но по-хорошему, его ведут как раз на свежак v2. Я гляну что можно сделать.

**Comment by gela-d** [comment]
@h4 круто :) но все равно спасибо за бдительность!
