### ISSUE TITLE
И вновь prose.io - не позволяет отправить реквест

### ISSUE THREAD

**Issue by raining** [bem/bem-method#221]
Здравствуйте!

Попыталась предложить правку, например вот на эту страницу: http://prose.io/#bem/bem-core/edit/v2/common.docs/intro/intro.ru.md

Нажимаю Submit Change Request, и ничего не отправляется, а как будто висит.

**Comment by zxqfox** [comment]
Related #217

**Comment by tavriaforever** [comment]
@gela-d

**Comment by gela-d** [comment]
@raining А модешь сейчас еще раз попробовать? И что за браузер?

**Comment by raining** [comment]
Все равно висит.
Система: 
`uname -a`
`Linux rw-ThinkPad-X201 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
Браузер:
`Google Chrome Version 40.0.2214.111 (64-bit)`

Даже скриншотиком поделюсь :)
Дальше указанного состояния не идет.
Там просто с вот этой таской связано https://github.com/bem/bem-core/issues/896 

![snapshot2](https://cloud.githubusercontent.com/assets/886404/6523153/1afcffb8-c3fe-11e4-8ac6-f06809215703.png)

**Comment by gela-d** [comment]
@raining А справа внизу зеленая кнопка авторизации на гитхаба висит? Или ты авторизована?
Проблему воспроизвели для пользователей, которые не в организации  bem, пока ищу в issues  самого proise.io аналогичную задачу.

**Comment by raining** [comment]
@gela-d да, авторизована.

**Comment by gela-d** [comment]
@raining Если честно, то я не знаю чем могу помочь. Могу посоветовать поставить isslue с детальным описанием сюда - https://github.com/prose/prose/issues/
А пока все проблемы присылать нам в issues.

**Comment by raining** [comment]
@gela-d 

Спасибо за попытку решения :) если что-то еще найдется, напишу на github issues.

**Comment by gela-d** [comment]
@innabelaya Инна, а ты не получаешь отбивок от issue, если туда поставить лэйбл `docs`?

**Comment by innabelaya** [comment]
@gela-d Нет. Но, думаю, что это можно попробовать как-то настроить. Мне просто сваливаются все отбивки.

**Comment by gela-d** [comment]
@innabelaya Глянула в настройках, не нашла возможности подписки. Но то, что все читаешь - хорошо :)

**Comment by tavriaforever** [comment]
We need create task and try to repair, @gela-d create?

**Comment by gela-d** [comment]
@tavriaforever О чем должна быть задача и что именно ты хочешь чинить? :)
