### ISSUE TITLE
Feedback for "Учимся у разработчиков интерфейсов Яндекса"

### ISSUE THREAD

**Issue by n1k1c4** [bem/bem-method#224]
"Английская версия статьи доступна здесь."

Слово "здесь" идёт ссылкой на ту же самую страницу на которой находишься, т. е. на https://ru.bem.info/articles/yandex-frontend-dev/

**Comment by dab** [comment]
@n1k1c4 спасибо, исправим

**Comment by gela-d** [comment]
https://ru.bem.info/articles/yandex-frontend-dev/
