### ISSUE TITLE
Feedback for "Блок image"

### ISSUE THREAD

**Issue by rtxrulez** [bem/bem-method#225]
Опять чего то картинки не грузятся.  (
http://awesomescreenshot.com/0b54mr7813
Ос windows 7 32bit
chrome
Версия 43.0.2330.4 canary

**Comment by sipayRT** [comment]
@tavriaforever

**Comment by tavriaforever** [comment]
Спасибо за фидбек, мы это уже починили и в ближайшее время выкатим на сайт фикс.

**Comment by gela-d** [comment]
Fixed https://en.bem.info/libs/bem-components/v2.1.0/desktop/image/
