### ISSUE TITLE
Орфографическая ошибка на странице "Определения"

### ISSUE THREAD

**Issue by skparallax** [bem/bem-method#239]
>Мы используем одно подчеркивание для `отделение` имени модификатора от имени блока и еще одно подчеркивание для отделения значения модификатора от его имени.

Мы используем одно подчеркивание для `отделения` имени модификатора от имени блока и еще одно подчеркивание для отделения значения модификатора от его имени.

**Comment by dab** [comment]
@skparallax спасибо, поправим

**Comment by dab** [comment]
https://github.com/bem/bem-method/commit/f99442a59388a6c17ff062ccf7eaee4f6a23ec4e
