### ISSUE TITLE
Feedback for "Проекты на БЭМ"

### ISSUE THREAD

**Issue by f0rmat1k** [bem/bem-method#242]
Ребят, отправил на info@ письмо с предложением о размещении https://github.com/f0rmat1k/bemy в списке, чет никто не ответил. Можно какой то фидбек, пожалуйста?

**Comment by zxqfox** [comment]
@f0rmat1k Возможно, имеет смысл так же начать пилить bem-cli (или что-то типа того).

/cc @tadatuta

**Comment by tadatuta** [comment]
@f0rmat1k привет! разместим, конечно. спасибо!

**Comment by f0rmat1k** [comment]
@tadatuta привет. От меня требуется какое-то краткое описание проекта?

**Comment by tadatuta** [comment]
@f0rmat1k если пришлешь PR в https://github.com/bem/bem-method/blob/bem-info-data/projects/projects.ru.md будет совсем круто. единственная просьба — чтобы в тексте было что-то в духе «если вы давно хотели перейти с bem-tools на ENB, но не могли, т.к. вам нужна была команда `bem create`, то теперь...»

**Comment by zxqfox** [comment]
@alexbaumgertner Расскажешь, почему ты не смог перейти на enb в субботу ;-) Ну, кроме того, что либа завязана на bem-tools.

**Comment by f0rmat1k** [comment]
@tadatuta [готово](https://github.com/bem/bem-method/pull/243)

**Comment by f0rmat1k** [comment]
спасибо
