### ISSUE TITLE
Feedback for "Создаем свой проект на БЭМ"

### ISSUE THREAD

**Issue by kaineer** [bem/bem-method#246]
В разделе https://ru.bem.info/tutorials/start-with-project-stub/#Миксы-блоков-и-элементов
после добавления библиотек, подгрузки пакетов через bower и перезапуска сервера
полное ощущение, что данные блока box из каталога libs/j/blocks не подтягиваются.

.bem/make.js подправил, пытался и в head.deps.js добавлять зависимость от блока box - не тянутся стили, в _index.css не попадают.

Текущее состояние можно посмотреть здесь:
https://bitbucket.org/kaineer/hello-bem/src/9f4ada04585db3358bd12dded17b03f4d35b0b96/

**Comment by kaineer** [comment]
По-моему, понял. Если используем для компиляции enb, нужно подправить ещё и .enb/make.js, про это в тексте ничего не сказано.

**Comment by tadatuta** [comment]
@kaineer Спасибо, поправим!

// cc @innabelaya

**Comment by innabelaya** [comment]
@kaineer @tadatuta спасибо! взяла в работу, поправлю.
