### ISSUE TITLE
BEMJSON: `elemMods`, do we really need it?

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-method#250]
As @tadatuta said: It's made for consistency with template engines. I can say that I didn't see atm a real reason why these private template things exposed to end-user of `BEMJSON` format.

I feel that a lot of tools now using this (at least `bem-xjst`). But is there real requirement to differentiate `mods` with `elemMods`?

**Comment by tadatuta** [comment]
@zxqfox 

sure, it's real requirement and not something internal:
```js
block('b1').elem('e1').content();
block('b1').mod('m1', 'v1').elem('e1').content();
block('b1').elem('e1').elemMod('m1', 'v1').content();
block('b1').mod('m1', 'v1').elem('e1').elemMod('m1', 'v1').content();
```
will all match different nodes.

**Comment by zxqfox** [comment]
You talking about XJST specific things. Let's rewrite it:
```
block('b1').elem('e1').content();
block('b1').mod('m1', 'v1').elem('e1').content();
block('b1').elem('e1').mod('m1', 'v1').content();
block('b1').mod('m1', 'v1').elem('e1').mod('m1', 'v1').content();
```

Still all the same (just `mod` used instead of `elemMod` inside `elem`). It's a xjst troubles, not bemjson format itself.

**Comment by tadatuta** [comment]
@zxqfox 
> block('b1').mod('m1', 'v1').elem('e1').mod('m1', 'v1').content();

:(

**Comment by zxqfox** [comment]
@tadatuta 
Is it possible:
```
elemMod('v1', 'm1').mod('m1', 'v1').elem('e1').block('b1').content(); ?
```
Does somebody use it?

**Comment by tadatuta** [comment]
@zxqfox e.g.
```js
elemMod('v1', 'm1')(
   content()(),
   mod('m1', 'v1').content()()
)
```

**Comment by zxqfox** [comment]
@tadatuta Satanic thing. What does it means?

**Comment by tadatuta** [comment]
set some content for `b1__e1_v1_m1` when it's inside `b1` without modifiers and something else for same element with the same modifier but in case it's inside `b1_m1_v1`

**Comment by zxqfox** [comment]
So it's semantically the same as:
```
block('b1')(
  elem('e1).elemMod('v1', 'm1').content()(),
  mod('m1', 'v1').elem('e1').elemMod('v1', 'm1').content()()
)
```
?

Don't see why we need separate `elemMod`.

**Comment by zxqfox** [comment]
@tadatuta Oh, btw. It's a good bad example of usage cascade in BEMHTML :smirk_cat:

**Comment by tadatuta** [comment]
@zxqfox it's absolutely the same example as
```css
.my-block_state_active .my-block__elem
{
    color: red;
}
```

**Comment by zxqfox** [comment]
@tadatuta Nope, actually. Your example is:
```
.block__elem_v1_m1 {
}
.block__elem_v1_m1 :inside?(block_m1_v1) {
)
```
