### ISSUE TITLE
Ссылка на 4ый выпуск дайджеста в меню отрывает 3ий выпуск.

### ISSUE THREAD

**Issue by Guria** [bem/bem-method#251]
https://ru.bem.info/blog/digest-4/ - 404
в меню раздела Блог пункты дайджест 3 и дайджест 4 указывают на https://ru.bem.info/blog/digest-3/

**Comment by tadatuta** [comment]
@Guria спасибо, поправили

**Comment by tadatuta** [comment]
cc @dab
