### ISSUE TITLE
What about linter / checker of BEM structure of CSS code ?

### ISSUE THREAD

**Issue by fabm22** [bem/bem-method#269]
Hi, is there some tooling for checking the structure of CSS code following BEM approach and having and some warnings if there are errors?

Thanks a lot.

**Comment by Guria** [comment]
Please address you question to [forum](https://en.bem.info/forum/)

**Comment by tavriaforever** [comment]
Added your question to bem forum https://en.bem.info/forum/8/

**Comment by fabm22** [comment]
Thanks !
