### ISSUE TITLE
Feedback for "Собираем статическую страницу на БЭМ"

### ISSUE THREAD

**Issue by err0rgit** [bem/bem-method#272]
на 3 шаге вот такая неприятность(
https://ru.bem.info/tutorials/quick-start-static/

![2015-07-06 22-39-35](https://cloud.githubusercontent.com/assets/7541667/8531440/0a7e1216-2430-11e5-8ac9-19fdbc0b3aa4.png)

**Comment by tadatuta** [comment]
@err0rgit проверил по шагам, у меня не воспроизводится.
Скорее всего возникла  проблема при установке npm-зависимостей. Как вариант это может быть связано с тем, что node.js или npm устанавливался от суперпользователя или `ENB` установлен глобально.

Помог бы полный лог процесса установки.

**Comment by err0rgit** [comment]
@tadatuta спасибо, посмотрю. Если повторится, скину лог

**Comment by gela-d** [comment]
@err0rgit все получилось? Могу закрыть issue?

**Comment by err0rgit** [comment]
@gela-d да, спасибо!
