### ISSUE TITLE
Feedback for "Learning to Love BEM"

### ISSUE THREAD

**Issue by andreas-becker** [bem/bem-method#274]
> There might be a modifier e.g. .my-element__sub-elelement—highlighted (the 2 hyphens denote a modifier state).

should be changed to:

> There might be a modifier e.g. .my-element__sub-element—highlighted (the 2 hyphens denote a modifier state).

The name of the sub-element has a typo.

**Comment by gela-d** [comment]
Thank's, fixed - https://en.bem.info/articles/learning-to-love-bem/
