### ISSUE TITLE
Feedback for "Организация файловой системы"

### ISSUE THREAD

**Issue by Gurylev** [bem/bem-method#285]
Сохраняю страницу в читалку Pocket, чтобы почитать в метро, а оказывается, что сохранилась статья вообще с другим текстом "Представление блоков в файловой системе". Это, наверное, старая версия статьи? Но это в любом случае не то, что я ожидал для прочтения.
Как так может быть?

**Comment by gela-d** [comment]
Какая-то магия. Спасибо, разберемся.

**Comment by gela-d** [comment]
Есть подозрение, что эта бага в самом Pocket, так как считаем, что не очень хорошо сохранять версию страницы откуда-то их кэша, а не ту, с которой сохраняешь статью.
Написали им вопрос, пока ответа нет, но предполагаю, что это еще из-за того, что статья выкатилась два дня назад и, вполне возможно, у них, действительно, есть какой-то срок для кэша по каким-то причинам и, через некоторое время, они будут подтягивать уже обновленную версию.
Мы сами тоже тут мониторим этот момент, но пока, к сожалению, ничего точнее ответить не могу.

**Comment by Gurylev** [comment]
Спасибо большое за подробности! Буду ждать. Надеюсь, что-то они таки сделают. Может быть я могу как-то помочь ускорению процесса? Например, куда-то написать или поставить плюсик в ишью?)))

**Comment by gela-d** [comment]
@sipayRT Жень, подскажи, пожалуйста, куда ты писал про Pocket?

**Comment by tadatuta** [comment]
Как будто больше не воспроизводится.
