### ISSUE TITLE
Feedback for "Definitions"

### ISSUE THREAD

**Issue by battaglr** [bem/bem-method#289]
In the definition of [elements](https://en.bem.info/method/definitions/#element) the "contextual" links are broken:

- [A block or an element: when should I use which?](https://github.com/bem/bem-method/tree/bem-info-data/faq/faq.en.md#В-каком-случае-создавать-блок-в-каком-элемент)
- [Why does the BEM methodology not recommend using elements within elements?](https://github.com/bem/bem-method/tree/bem-info-data/faq/faq.en.md#Почему-в-БЭМ-не-рекомендуется-создавать-элементы-элементов-block__elem1__elem2)

*Also, it would be great if those questions were translated to english.*

**Comment by tadatuta** [comment]
@battaglr Thank you for report!
We're working on translation now. Stay tuned!

**Comment by gela-d** [comment]
@battaglr thanks!
@innabelaya Could you tell, do you have in plans translate faq to english? - https://github.com/bem/bem-method/blob/bem-info-data/faq/faq.ru.md
Now, we have russian links in this doc https://github.com/bem/bem-method/blob/bem-info-data/method/definitions/definitions.en.md

**Comment by innabelaya** [comment]
@battaglr Thanks!
@gela-d FAQ translation is in progress now. Links will be corrected after english version publishing.

**Comment by battaglr** [comment]
Awesome, thanks! Keep it up!
