### ISSUE TITLE
Feedback for "Сайт с нуля на полном стеке БЭМ-технологий"

### ISSUE THREAD

**Issue by vyushin** [bem/bem-method#296]
После строчек:
> Теперь страницу можно открыть по адресу: http://localhost:8080/desktop.bundles/index/index.html. Наш сборщик соберёт все необходимые зависимости, а по ним соберёт файлы нужных блоков > технологий.

enb не запускается. Падает с ошибкой:
http://take.ms/Q1HvY

node@0.12.7

**Comment by gela-d** [comment]
А папка libs с библиотекой bem-components есть на файловой системе проекта?

**Comment by vyushin** [comment]
@gela-d, нет, такой папки нет.

**Comment by sipayRT** [comment]
Видимо, ты не точно следовал инструкции и не установил себе bem-components, который притянул бы за собой bem-core, которого у тебя сейчас не хватает

**Comment by gela-d** [comment]
Все нужные команды описаны в этом разделе https://ru.bem.info/articles/bem-full-stack-site/#Создание-заготовки-проекта

**Comment by vyushin** [comment]
@sipayRT, @gela-d, я учёл ваши комментарии и попробовал вновь выполнить указания в инструкции. Заснял скринкаст, уж очень хочется довести tutorial до логического завершения. Будьте добры, взгляните не скринкаст, быть может он расскажет больше.
http://take.ms/x69SN

**Comment by tadatuta** [comment]
@vyushin Привет!
На четвертой минуте видео видно, что установка зависимостей упала с ошибкой `git is not installed or not in the PATH`. О необходимости наличия `git` написано в первом же абзаце https://ru.bem.info/articles/bem-full-stack-site/#Создание-заготовки-проекта

Для надежности настоятельно рекомендую выполнять все команды не в `cmd`, а в `git bash`, который устанавливается вместе с [git](https://git-scm.com/download/win).

**Comment by vyushin** [comment]
@tadatuta, действительно. GIT у меня установлен, по этому я машинально пропустил этот абзац, посчитав его выполненным. В PATH гита не было, да. 
Спасибо!
