### ISSUE TITLE
Feedback for "Организация файловой системы"

### ISSUE THREAD

**Issue by Erosanteros** [bem/bem-method#300]
В написании значений модификвторов допускаются точки? popup_target_anchor.ext
страица https://ru.bem.info/method/filesystem/

**Comment by Guria** [comment]
В теории, наверное, возможно. Но скорее всего это повлечёт множество нюансов при работе с такими модификаторами в CSS и методах выполняющих выборку по селектору в JS, как в браузерных, так и во всяких библиотеках. См., например, [использование таких символов в CSS](https://mathiasbynens.be/notes/css-escapes).

**Comment by blond** [comment]
> В написании значений модификвторов допускаются точки? 

Если следовать [соглашению по именованию](https://ru.bem.info/method/naming-convention/), то нет, не допускаются:

>* Имена БЭМ-сущностей записываются с помощью цифр и латинских букв в нижнем регистре.
* Для разделения слов в именах используется дефис (-).

В документе про организацию файловой системы говорится об именах файлов, а не модификаторов, и точка там используется не в имени модификатора, а в имени файла.

/cc @innabelaya Может как-то переформулируем, чтобы стало понятно что речь об именах файлов?

**Comment by blond** [comment]
Проверить можно с помощью библиотеки [bem-naming](https://github.com/bem/bem-naming).

```js
var bemNaming = require('bem-naming');

bemNaming.parse('block'); // { block: 'block' }
bemNaming.parse('block.ext'); // undefined
```

**Comment by innabelaya** [comment]
@blond @Guria спасибо, попробую переформулировать. 

@Erosanteros  Я так понимаю, сбивает абстрактная схема именования, где вместо примера конкретного расширения для файла (например, .css или .js) указывается `.ext` (.ext = extension)?

**Comment by Erosanteros** [comment]
да

14 августа 2015 г., 12:59 пользователь innabelaya <notifications@github.com>
написал:
