### ISSUE TITLE
Feedback for "Основные понятия"

### ISSUE THREAD

**Issue by FA73F0X** [bem/bem-method#304]
Возможно я ошибаюсь, т.к. только изучаю БЕМ ) Если посмотреть в "БЭМ-дерево", то там получается в БЭМ-дереве(search) в XML(<block:search>) в BEMJSON(block : 'search-form'). Почему в BEMJSON(block : 'search-form') а не BEMJSON(block : 'search') ?

**Comment by blond** [comment]
/cc @innabelaya надо сделать консистентно. 

Думаю, что везде должно быть `search-form`.

**Comment by FA73F0X** [comment]
Спасибо за ответ. Не думал, что так быстро ответят )

**Comment by innabelaya** [comment]
@FA73F0X Большое спасибо за фидбек! Поправили примеры на Github: https://github.com/bem/bem-method/pull/305
В скором времени информация обновится и на сайте.
