### ISSUE TITLE
Feedback for "Собираем статическую страницу на БЭМ"

### ISSUE THREAD

**Issue by Kreozot** [bem/bem-method#307]
В команде git clone в README.md указана ветка 1.2.0, а на странице всё ещё 1.0.0

**Comment by innabelaya** [comment]
@Kreozot спасибо за фидбек! Обязательно поправим в ближайшее время.

**Comment by innabelaya** [comment]
https://github.com/bem/bem-method/pull/310

**Comment by Kreozot** [comment]
:thumbsup:
