### ISSUE TITLE
Feedback for "Основные понятия"

### ISSUE THREAD

**Issue by Grawl** [bem/bem-method#309]
`</block:search>` вместо `</block:search-form>`

**Comment by blond** [comment]
Спасибо за фидбек! 

Исправил: https://github.com/bem/bem-method/commit/c6b4e720a79f63347cc080e2179424bad8bb3d92 https://github.com/bem/bem-method/commit/a997bdc519edaa6b0d4ab671f82739546ed39f6d. В ближайшее время обновится на сайте.
