### ISSUE TITLE
Feedback for "Filesystem"

### ISSUE THREAD

**Issue by ilyaigpetrov** [bem/bem-method#323]
`block-name_~_element-name`
I don't believe you actually mean `~` here.
Or add an explanation for this.

**Comment by gela-d** [comment]
@innabelaya

**Comment by innabelaya** [comment]
@ilyaigpetrov Thank you!

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-method/commit/285d07e8ba448d1f174a8ce7a38b5283cafe0b69
