### ISSUE TITLE
Feedback for "Соглашение по именованию"

### ISSUE THREAD

**Issue by ifeature** [bem/bem-method#325]
Исходя из документации, описывающей [Соглашение по именованию](https://ru.bem.info/method/naming-convention/), для повышения удобочитаемости кода, в особенности, когда дело касается "нагромаждения" значений класса, что описывает БЭМ-сущность, разделять их(значения) двойным пробелом:
```
<form class="form  form_login  form_theme_forest">
  <input class="form__input">
  <input class="form__submit  form__submit_disabled">
</form>
```

**Comment by tadatuta** [comment]
Мы постараемся решить проблему удобочитаемости кода с помощью шрифтов в новом дизайне. Добавлять лишние пробелы в код все-таки не хочется...

**Comment by ifeature** [comment]
Я бы так категорично это проблемой не называл. Это скорее уж очень субъективное наблюдение.
---
С уважением.
