### ISSUE TITLE
Feedback for "The history of BEM" - typos

### ISSUE THREAD

**Issue by jmarkevicius** [bem/bem-method#331]
“At the same time, even bigger project was started Yaru — a blogging platform, a place for people to interact, to share, to read and to engage.” - there should be a dash before ‘Yaru’.

“At Yandex, a front-end developers usually supports more than one project.” - ‘supports’ should read ‘support’.

“Code generation was an important step forward; from this point onwards, we don't have to maintain depenpencies manually.” - ‘depenpencies’ should read ‘dependencies’.

“These's a summary of our study available (in Russian): completely independent blocks.” - ‘These’s’ should read ‘There’s’.

“…and based mostly on semantical criteria” - ‘semantical’ should read ‘semantic’.

“It took Yandex a while to figure out what's important and what not.” - ‘what’ should read ‘what’s’.

“BEM is a collection of ideas and methods, a methodology.\ Each company and each team may integrate it into an existing workflow gradually, finding out what works best for them.” - there’s a ‘\’, which is probably not intended.

**Comment by tadatuta** [comment]
@jmarkevicius Thank you very much!
