### ISSUE TITLE
Feedback for "The history of BEM"

### ISSUE THREAD

**Issue by pdxbmw** [bem/bem-method#332]
Just a heads-up on a typo in the [What's inside?](https://en.bem.info/method/history/#whats-inside) section. Second paragraph, first sentence currently reads `element inability` and I believe it's meant to read `element's inability`.

**Comment by tadatuta** [comment]
@pdxbmw Thank you!

**Comment by pdxbmw** [comment]
@tadatuta  My pleasure. This is outstanding documentation.
