### ISSUE TITLE
Feedback for "Frequently asked questions"

### ISSUE THREAD

**Issue by pdxbmw** [bem/bem-method#333]
Another heads-up on a typo in [What is the difference between BEM and Web Components?](https://en.bem.info/faq/#what-is-the-difference-between-bem-and-web-components) section. Under **Template execution**, second bullet point, second sentence currently reads `This let us` and I believe it's meant to read `This lets us`.

**Comment by pdxbmw** [comment]
Never mind. I believe I'm just reading it incorrectly. It's past tense, not present tense.

**Comment by pdxbmw** [comment]
Reading it again, I'm really not sure. It seems like it should be present tense – `lets`, not `let`.

**Comment by tadatuta** [comment]
You are right, fixed, thank you!

**Comment by pdxbmw** [comment]
👍
