### ISSUE TITLE
Feedback for "Применение методологии для решения задач веб-разработки"

### ISSUE THREAD

**Issue by BeklievParviz** [bem/bem-method#336]
Страница: https://ru.bem.info/method/solved-problems/
Ошибка в слове "получать **самодокуметируемый** код."
Отсутствует буква "н".

Скриншот: https://yadi.sk/i/Y-MmQ3AcjkNys
![Скриншот](https://goo.gl/WVWmxv)

**Comment by gela-d** [comment]
Спасибо!
+ @innabelaya

**Comment by innabelaya** [comment]
@BeklievParviz Спасибо!
Исправили https://github.com/bem/bem-method/commit/0b56ac623b5dccecc9786bbd005135f3baaffcd3

**Comment by BeklievParviz** [comment]
Всегда пожалуйста :wink:
