### ISSUE TITLE
Feedback for "Собираем статическую страницу на БЭМ"

### ISSUE THREAD

**Issue by alukos** [bem/bem-method#349]
https://github.com/bem/bem-method/blame/bem-info-data/articles/quick-start-static/quick-start-static.ru.md#L250
Может быть:
Для добавления к **блоку** `input` CSS правил, уже реализованных в **элементе `input` блока** `hello`
?

**Comment by innabelaya** [comment]
Спасибо большое! Поправили: https://github.com/bem/bem-method/commit/765ab4cb8fda0b72d021ea3a6fe9eb96d03e878b
