### ISSUE TITLE
Feedback for "FAQ"

### ISSUE THREAD

**Issue by trikadin** [bem/bem-method#351]
Странный пункт. Ощущение, будто вопрос и ответ вообще не связаны друг с другом.
https://ru.bem.info/faq/#Почему-нельзя-писать-div-classblock_mod-вместо-div-classblock-block_mod-если-имя-модификатора-уже-содержит-всю-информацию-о-блоке

**Comment by tadatuta** [comment]
@trikadin Спасибо, поправим!

// cc @innabelaya
