### ISSUE TITLE
Feedback for "File system organization"

### ISSUE THREAD

**Issue by raulmontejo** [bem/bem-method#354]
> During the build process, all the generic CSS rules for the button will be included in the `desktop.css` file from the `common` level, and the redefined rules from the `desktop` level.

Shouldn't that be `button.css`?

**Comment by tadatuta** [comment]
@raulmontejo no. the idea is that build system will collect files from all the blocks (button, etc) to one single file. And in the example its name is `desktop.css` to show that it's a bundle which gathers blocks for desktop platform.
