### ISSUE TITLE
Feedback for "Frequently asked questions"

### ISSUE THREAD

**Issue by aboutjquery** [bem/bem-method#355]
Hello,

I like the css bem method, but i just cant find a good method to naming the html markup to be more neat, for example, what if i have a block inside block and a other block inside it?

Here is the example code (i cant output the html, please forgive me)

<pre>
.page
  .off-canvas-right
    .off-canvas-right-header -- i think i should use a block at this header
      .off-canvas-right-logo -- i think logo is also a block in this case
        .off-canvas-right-logo__img -- element
        /.off-canvas-right-logo__img
      /.off-canvas-right-logo
    /.off-canvas-right-header

    .off-canvas-right-footer -- i think i should use a block at this footer
    /.off-canvas-right-footer
  /.off-canvas-right
/.page
</pre>

As above code, am i doing right? i use block (off-canvas-right) + block (header) to name a block (off-canvas-right-header)

If i doing right, do i need change off-canvas-right to be page-off-canvas-right to be more neat? I dont think i am doing right...but i would like o make all of the html code much neat.

So what is a good naming method on this case? Please give me some suggest, thank you very very much, and is there any full css naming website or example? Thanks :)

**Comment by tadatuta** [comment]
Hey! Here's a BEM website: https://en.bem.info/
Take a look at Methodology section and visit FAQ. These should answer a lot of questions.

As for your current questions:
1. You may put blocks inside other blocks.
2. You may put blocks inside elements.
3. You may [mix](https://en.bem.info/method/key-concepts/#mix) different blocks or elements on same DOM node.

So you code can look like this:
```html
<body class="page">
  <div class="off-canvas-right">
    <header class="header off-canvas-right__header"> <!-- mix with off-canvas-right__header element is optional  -->
      <div class="logo header__logo">
        <img class="logo__img">
      </div>
    </header>
    <footer class="footer"></div>
  </div>
</body>
```

**Comment by aboutjquery** [comment]
Hello, thank you very very much :)

I have few question about this case.

<pre>
.page
  .off-canvas-right
    .header .off-canvas-right__header
      .logo .header__logo
        .logo__img
        /.logo__img
      /.logo .header__logo
    /.header .off-canvas-right__header

    .footer off-canvas-right__footer
      .logo .footer__logo
        .logo__img
        /.logo__img
      /.logo .footer__logo
    /.footer off-canvas-right__footer
  /.off-canvas-right
/.page
</pre>

Question 1: Let say the logo, now the logo class become <code>logo header__logo</code>.

Which class i should use at css file? <code>logo</code> or <code>header__logo</code>? I think is <code>header__logo</code>, if yes, the <code>logo</code> class in this case is use for namespace and wont use at the css file? (for mix the block or element)

Question 2: And if i have another logo at footer, i cant name it as <code>logo</code>, because next level will be <code>logo__img</code>, and if i use same class at header and footer, i cant style each logo without nest css, what solution is good for this case?

Question 3: As above code, we have not mix <code>page</code> and <code>off-canvas-right</code>, which case we can skip this step?

I am going to read more info to learning css bem, Thank you soooooo much :)

**Comment by tadatuta** [comment]
> Question 1: Let say the logo, now the logo class become logo header__logo.
Which class i should use at css file? logo or header__logo? I think is header__logo, if yes, the logo class in this case is use for namespace and wont use at the css file? (for mix the block or element)

You should use `logo` for universal styles for logotype (like width, height, etc) and `header__logo` for styles just for logo inside `header` (e.g. positioning: margin, padding, etc). So there will be possibility to reuse same block in different parts of a page.
Hope it also answers the second question.

> Question 3: As above code, we have not mix page and off-canvas-right, which case we can skip this step?

Try to ask yourself about each property you add to any block: if it's universal one (so you'll be able to reuse this block with all styles) — it should be one entity (block or element). Add when you see some styles specific to this particular usecase it's a hint to add a mix.

But you may add mixes just when you really need to reuse a block at some other place.

**Comment by aboutjquery** [comment]
Thank you very very much :)
