### ISSUE TITLE
Feedback for "Naming convention"

### ISSUE THREAD

**Issue by romanmikhailov** [bem/bem-method#356]
> No namespace style
>
>  `_available`
>
> This style is characterized by the absence of a *block name* before a modifier. Such a scheme puts limitations on the use of mixes, as it makes it impossible to determine what block a modifier belongs to.

I think that need replace "block name" (bolded in quotation) with "block or element name". It's probably will be more clearly.
The same in original Russian version.

Thank you.

**Comment by tadatuta** [comment]
cc @innabelaya

**Comment by innabelaya** [comment]
@romanmikhailov Thank you! Corrected.
