### ISSUE TITLE
Feedback for "Using BEM to solve common issues in web development"

### ISSUE THREAD

**Issue by mdahlstrand** [bem/bem-method#358]
The documentation (on https://en.bem.info/method/solved-problems/) says:

	`nav__item_active` will indicate the name of a modifier for the item element.

Shouldn't the modifier class use `--`, i.e. `nav__item--active`?

Thanks for good documentation otherwise!

**Comment by tadatuta** [comment]
Hi! Thank you for feedback!

Actually you may use any notation (see https://en.bem.info/method/naming-convention/#alternative-naming-schemes) but classic separator is underscore — it is convenient to use one underscore for modifier and another one for it's value, like this:
```
nav_size_small
nav_size_large
```
Which means: modifier `size` with the value `small`/`large` of `nav` block.

**Comment by mdahlstrand** [comment]
I'm confused - which convention outlined in the documentation is the documentation using? Seems like it's not using `block__el_modName_modVal` either ("CamelCase style" on your link).

I definitely think one style (either, but I definitely prefer @csswizardry's BEM style) should be picked and used throughout the documentation - now it's using a "non-standard" third... :confused:

**Comment by tadatuta** [comment]
`b__e--m` is fine but it says nothing about modifiers with values, which is quite handy for some cases.

**Comment by blond** [comment]
@tadatuta you can use `_` with convention by Harry Roberts to separate modifier name from modifier value.

```
nav--size_small
nav--size_large
```

**Comment by mdahlstrand** [comment]
Yeah, I've done what @blond said in the past too, definitely like it (and `--`) as it's clearer what's what.
