### ISSUE TITLE
Feedback for "История создания БЭМ"

### ISSUE THREAD

**Issue by artinnok** [bem/bem-method#364]
![screenshot from 2015-12-14 17-46-32](https://cloud.githubusercontent.com/assets/8825727/11783912/b4ae3e4a-a28a-11e5-8269-006aabf5d2e8.png)

**Comment by innabelaya** [comment]
@artinnok спасибо! Поправила - https://github.com/bem/bem-method/commit/86928596c66f79189d6b00aeb29bbcee0d8490d0
