### ISSUE TITLE
Feedback for "FAQ"

### ISSUE THREAD

**Issue by 3ABAPKA** [bem/bem-method#365]
# Здравствуйте!

Не нашел ответа на свой вопрос ни в ["FAQ"](https://ru.bem.info/faq/), ни в ["Форуме"](https://ru.bem.info/forum/) поэтому пишу сюда.
Пытаюсь изучать БЭМ, за несколько дней написал [простою верстку в три колонки ](https://github.com/3ABAPKA/The-first-project-on-validation.git), ещё несколько дней потратил на то, чтоб залить её на Github.
Прошу уделить внимание **знающих и понимающих БЭМ специалистов** и высказать всё, что вы думаете. Указать на недостатки, нарушения методологии и всего прочего. Если не сильно лень, то высказать наставления...
Заранее спасибо....

**Comment by tadatuta** [comment]
Так а вопрос-то в чем был, на который не нашелся ответ? :)

**Comment by tadatuta** [comment]
Сделал быстрое ревью в [пулл-реквесте](https://github.com/3ABAPKA/The-first-project-on-validation/pull/1).

**Comment by 3ABAPKA** [comment]
1. Постарался учесть замечания, указанные в [review #1](https://github.com/3ABAPKA/The-first-project-on-validation/pull/1).

2. Добавил скрипт галереи в качестве учебы или практики (тут есть не принятые в БЭМ моменты, типо "id", но этого требовала инициализация скрипта. И еще, часто требуется не написать что-то, а прикрутить чьё-то...)

3. Длинные комментарии я тоже не удалял, т.к. они не мои..

4. Убрал `'написания тегов прямо в BEMJSON,'` и вынес их в шаблоны.


Если не трудно взгляните!

**Comment by tadatuta** [comment]
чуть откомментировал в предпоследнем коммите. последний коммит, насколько я понимаю, стоит полностью удалить?

**Comment by 3ABAPKA** [comment]
Переделал с учетом замечаний!
Посмотрите пожалуйста, получилось у меня или нет!

**Comment by tadatuta** [comment]
прокомментировал в коммитах

**Comment by 3ABAPKA** [comment]
Не выходит справится с `.borschik`... Информации крайне мало, если имеете связь с разработчиками, посоветуйте сделать "песочницу"...
В какой из файлов следует писать конструкцию типо:
```
var prj = {};
/* borschik:include:../../libs/coverflow-container/coverflow-container/sly.min.js */
```
Мной создан файл `.borschik` в корне проекта ...
Пробовал `var prj = {}; и т.д.` в файлах `index.bemjson.js`, `index.js`, `.borschik`, а так же различные конструкции и в `git Bash` типо: 
`borschik --input=libs/coverflow-container/coverflow-container/sly.min.js --minimize=no`
`borschik --input=desktop.bundles/index/index.js --minimize=no`
`borschik --input=index.js --minimize=no`
Ну и всё в таком духе...

Кроме того. заглянув в файл `index.js` увидел в нём много подключаемых скриптов, в том числе и `/* begin: ../../libs/bem-core/common.blocks/jquery/jquery.js */` однако до тех пор пока не впишешь в `index.bemjson.js` строчку = 
`{ elem: 'js', url: 'http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' }` 
сторонний скрипт, требующий `jquery` не работает. = 
Где можно поискать ошибку, в чем может быть причина?

**Comment by 3ABAPKA** [comment]
@tadatuta ?

**Comment by tadatuta** [comment]
`/* borschik:include:../../libs/coverflow-container/coverflow-container/sly.min.js */` нужно писать в JS-файл блока, которому нужна данная библиотека. В простом случае достаточно просто создать блок `sly` и в нем одну эту строку, а потом просто добавить `sly` в `deps.js` его родителя.

Если же для этой библиотеки необходима `jQuery`, то можно сделать так:
```js
modules.require(['jquery'], function($) {
    /* borschik:include:../../libs/coverflow-container/coverflow-container/sly.min.js */
});
```

Может оказаться, что библиотека ожидает `jQuery` не в `$`, а в `jQuery` или, как вариант, обязательно в `window.jQuery`. Тогда нужно соответственно поправить код выше.

**Comment by 3ABAPKA** [comment]
У меня ничего не вышло, прошу помощи [8273a94](https://github.com/3ABAPKA/The-first-project-on-validation/commit/8273a94671821393170ba75cae1139983b1e3cdf).

**Comment by 3ABAPKA** [comment]
help me pls

**Comment by 3ABAPKA** [comment]
Ни у кого нет желания помочь?

**Comment by tadatuta** [comment]
@3ABAPKA можешь, пожалуйста, сформулировать конкретный вопрос на https://ru.bem.info/forum/ ?

**Comment by 3ABAPKA** [comment]
@tadatuta, сорь, думаю на форуме это будет совсем не к месту. Ведь в данном случае проблема во мне. Это я не понимаю как использовать. Метод "тыка" результата не дал. Учиться не у кого. Хотелось бы чтоб человек нашел время, посмотрел мой проект, и конкретно на примере мне б показал как делать и в чем моя ошибка.
Т.е. это то, чем являлись все Ваши до этого пояснения, за которые я безмерно благодарен. Когда я писал фразу "Ни у кого нет желания помочь?", конечно, намекал на Вас. Но если у Вас нет времени, или другие причины, то просто скажите, я всё по удаляю и тревожить больше не буду. Возможно в будущем вернусь к этому.
P.S.
Если интересно, то считаю, что Ваши уроки и помощь зря не прошли. На днях я сверстал на основе `project-stub` несколько страниц. Сумел использовать ряд компонентов из `bem-components` мне очень понравилось. 
Конечно, специалист Вашего уровня, найдет там уму недочетов. Но я в восторге. Быстро, легко, доступно. И даже не было проблем с внедрением верстки в CMS.

**Comment by tadatuta** [comment]
на самом деле форум ровно для вопросов по технологиям и создан ;)
и ответы там накапливаются и помогут другим пользователям, а здесь потеряются.

к тому же там сообщения читает гораздо больше народу, так что шанс получить оперативный ответ куда выше.

у меня сейчас весьма напряженный график, так что я пока не могу погрузиться в код, через пару  недель должно стать попроще, но, думаю, на форуме ответят куда раньше.

**Comment by 3ABAPKA** [comment]
Спорить не стану. Возможно Вы правы. Однако я считаю, что пока уровень у меня не тот. Как отвечают на форумах я знаю (чет типо = "гугль тебе в руки"), особенно когда вопрос "выеденного яйца" не стоит. Я читал вопросы, которые там задают, какие там бывают ответы. Считаю, что у меня проблема легче и нечего форум захламлять.

В качестве наполнения форума дельной информацией - я выставлю на него уже решенную проблему.

Поэтому я подожду, может мне повезет.))))

**Comment by vithar** [comment]
Чтобы повезло — надо пиалой вопрос на форум.
