### ISSUE TITLE
Feedback for "FAQ"

### ISSUE THREAD

**Issue by igoradamenko** [bem/bem-method#371]
В разделе [Можно ли объединять тег и класс в селекторе? Например, `button.button`](https://ru.bem.info/faq/#Можно-ли-объединять-тег-и-класс-в-селекторе-Например-buttonbutton) во втором фрагменте кода неправильный модификатор. Судя по описанию дальше, должен быть `.button_mod`, а не `.button_active`.

P.S.: Может, надо было сразу PR сделать? Или лучше так, а вы сами поправите? (спрашиваю на будущее, вдруг ещё что будет :))

**Comment by igoradamenko** [comment]
В английской версии аналогичная проблема.

**Comment by innabelaya** [comment]
@igoradamenko спасибо! Обязательно поправим!
По поводу PR: правки к русской версии можете присылать сразу в pull request'ах. Если всё будет правильно, мы  обязательно их вольем. 
Переводы на английский у нас генерятся автоматически, поэтому пока правки в английский документы можем вносить только мы.

**Comment by igoradamenko** [comment]
:+1:

**Comment by innabelaya** [comment]
Исправила. В ближайшем будущем обновится на сайте. https://github.com/bem/bem-method/commit/c94ee1f15342afba881af4efac2cd804685686c2
