### ISSUE TITLE
Feedback for "История создания БЭМ"

### ISSUE THREAD

**Issue by AlexanderDemko** [bem/bem-method#376]
Директория каждой технологии имеет свою структур**а**.
Все файлы (css, js, html, xsl), относящиеся к блоку, хранятся в его директори**ю**:

**Comment by innabelaya** [comment]
@AlexanderDemko Спасибо! Исправили https://github.com/bem/bem-method/commit/3c3b52e5406b2540d06e9468a5e7b953ae3693e3. В ближайшем будущем обновится на сайте.
