### ISSUE TITLE
Feedback for "Основные понятия"

### ISSUE THREAD

**Issue by sg-mamedova** [bem/bem-method#379]
Здравствуйте, 
хотелось бы конкретный пример (с кодом html/css) в разделе, где описывается Микс
https://ru.bem.info/method/key-concepts/#Микс

**Comment by tadatuta** [comment]
Пример есть в последующих документах. Например, https://ru.bem.info/method/solved-problems/#Как-разместить-несколько-сущностей-на-одном-dom-узле-и-избежать-copy-paste
