### ISSUE TITLE
Feedback for "Декларации в БЭМ"

### ISSUE THREAD

**Issue by v-bornov** [bem/bem-method#380]
Здравствуйте!
Увидел опечатку в разделе Сложение деклараций
На схеме вместо второго + должно быть =

Сейчас
Декларация 1      +      Декларация 2      +      Декларация 3

А нужно
Декларация 1      +      Декларация 2      =      Декларация 3

**Comment by tadatuta** [comment]
@v-bornov Спасибо, исправил.
