### ISSUE TITLE
Feedback for "Применение методологии для решения задач веб-разработки"

### ISSUE THREAD

**Issue by ildaribragimov** [bem/bem-method#385]
`<ul class="nav">
    <li class="nav__item nav__item_active"><a class="nav__link">One</a></span></li>
    <li class="nav__item"><a class="nav__link">Two</a></li>
    <li class="nav__item"><a class="nav__link">Three</a></li>
</ul>`

Не могу найти открывающий тег "span". Скорее всего, у вас опечатка.

**Comment by tadatuta** [comment]
Спасибо, исправлено в https://github.com/bem/bem-method/commit/9b8517ed14de4806ca4095073fcc9cdadd3c3ac6
