### ISSUE TITLE
Element name section missing underscore?

### ISSUE THREAD

**Issue by tatwater** [bem/bem-method#397]
At [https://en.bem.info/methodology/naming-convention/#element-name](https://en.bem.info/methodology/naming-convention/#element-name), is the sentence "If a block has several identical elements, such as in the case of menu items, all of them will have the same name `menu_item`," supposed to say `menu__item` or am I missing something?

**Comment by vithar** [comment]
Fixed, thank you. Will update production site soon.

**Comment by tatwater** [comment]
Thanks!
