### ISSUE TITLE
BEM tree has no Elements

### ISSUE THREAD

**Issue by dotnetCarpenter** [bem/bem-method#401]
>https://en.bem.info/methodology/key-concepts/#bem-tree

The DOM example suggest that BEM has no Elements. After reading [a different article](https://www.smashingmagazine.com/2014/07/bem-methodology-for-small-projects/) I would change the BEM tree to:
```xml
<block:header>
    <block:logo/>
    <block:search-form>
        <element:input/>
        <element:button/>
    </block:search-form>
    <block:lang-switcher/>
</block:header>
```
And the DOM tree to:
```html
<header class="header">
    <img class="logo">
    <form class="search-form">
        <input class="search-form__input" type="input">
        <button class="search-form__button" type="button"></button>
    </form>
    <div class="lang-switcher"></div>
</header>
```

I might be mistaken but right now there is no guideline to how **E**lements fit into a BEM tree.

**Comment by tadatuta** [comment]
@dotnetCarpenter  you are right, thank you! we'll update the docs.

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-method/pull/435/files
