### ISSUE TITLE
Feedback for "Создаем свой проект на БЭМ"

### ISSUE THREAD

**Issue by Bot8** [bem/bem-method#424]
Доброго времени суток. Спасибо за статью, отличный быстрый старт.

По ходу изучения статьи нашел несколько проблемных моментов

- В пункте
[BEMHTML-шаблоны](https://ru.bem.info/tutorials/start-with-project-stub/#bemhtml-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B) ([скриншот](http://storage2.static.itmages.com/i/16/0608/h_1465387229_3620837_6b414307d2.png))

желательно бы раскрыть блок
//...
а то он весьма не очевидный

- код 
`
elem('image')(
       tag()('img'),
       attrs()(function() {
            return { src: this.ctx.url };
        })
    )
`
не работает, мне помогло поменять его на
`
elem('image')(
  tag()('img'),
  attrs()(function(ContextChild, ctx) {
    return { src: ctx.content };
  })
)
`
- [в коде](https://gist.github.com/innabelaya/8914048) mods нужно заменить на elemMods 
([скриншот](http://storage4.static.itmages.com/i/16/0608/h_1465388113_2166793_d398e9201c.png))

**Comment by godfreyd** [comment]
Привет! Спасибо за  feedback. По второму замечанию сделал Pull Request https://github.com/bem/bem-method/pull/442. По первому, я повторил примеры из документации:
https://gist.github.com/innabelaya/3405ec7368aae6c3afe9#file-index-4-bemjson-js
https://gist.github.com/innabelaya/8913843
Код отработал хорошо. Напишите подробней, что вы делали, и что не сработало (желательно полный код).

**Comment by Bot8** [comment]
Привет. По второму пункту видимо я натупил, сейчас прошел заново все нормально.  

Но в одном моменте была проблема.
[Использование блоков из библиотеки](https://github.com/bem/bem-method/blob/bem-info-data/articles/start-with-project-stub/start-with-project-stub.ru.md#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%BE%D0%B2-%D0%B8%D0%B7-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8)

```javascript
{
   block: 'button',
   type: 'submit',
   content: 'Search'
}
```
генерирует блок  type="button" который форму не отправляет

```html
<button class="button button__control i-bem" data-bem="{"button":{}}" role="button" type="button">Search</button>
```
поменял декларацию на 
```javascript
{
   block: 'button',
   mods: {
      type: 'sumbit'
   },
   content: 'Search'
}
```
сгенерировалось 
```html
<button class="button button_type_sumbit button__control i-bem" data-bem="{"button":{}}" role="button">Search</button>
```
и кнопка стала отправлять форму

**Comment by godfreyd** [comment]
Спасибо, за комментарий! Сегодня поправим документацию.
