### ISSUE TITLE
Нет ссылки

### ISSUE THREAD

**Issue by AndGreen** [bem/bem-method#426]
В разделе https://ru.bem.info/methodology/build/#Инструменты-для-сборки не работает ссылка на [Декларативный JavaScript по БЭМ](https://ru.bem.info/events/beminar-july-2015/). Просьба поправить, спасибо.

**Comment by tadatuta** [comment]
Спасибо, правильная ссылка https://ru.bem.info/forum/-696/
Исправим в ближайшее время. Кстати, работа по сборке БЭМ-проектов на gulp продолжается, см. https://ru.bem.info/forum/782/ + https://github.com/gulp-bem
