### ISSUE TITLE
Feedback for Methodology→„Companies use BEM“

### ISSUE THREAD

**Issue by ihorzenich** [bem/bem-method#431]
I'm starting this thread for companies that would like to be referred to as „using BEM“.
If you can add link to repository with codestyle / build scripts or write a quote about „Why you recommend BEM“  - we will pick best ones and put them on site too.

To add your company to the list, please provide:
1. Company's international (English-based) logo in SVG format
2. Link to company's international site
3. Any confirmation that your company uses the BEM

or you can just create PR to 

1. https://github.com/bem-site/bem.info/blob/master/content/methodology/methodology.en.bemjson.js
2. https://github.com/bem-site/bem.info/blob/master/content/methodology/methodology.ru.bemjson.js
3. https://github.com/bem-site/bem.info/blob/master/content/methodology/methodology.uk.bemjson.js

**Comment by ihorzenich** [comment]
I'll start with myself: 

EPAM uses BEM too!
Not full-stack, like many other.
Now I can't provide examples of code due to NDA, maybe I can do it later…
 - Our SVG Logo: http://www.epam.com/content/dam/epam/global/logo_gray-blue_80px.svg 
 - Company URL: http://epam.com

Proofs:
 1. EPAM alredy added on getbem.com
 2. Internal email-correspondence with the head of Global Marketing / Marketing Delivery unit (on request)

**Comment by godfreyd** [comment]
Dear @ihorzenich, 

Thanks for provided information. 
Your website will be added in the list "Companies use BEM" once some adding functionalities will be implemented.

**Comment by ihorzenich** [comment]
@godfreyd I created a PR https://github.com/bem-site/bem.info/pull/134, please merge.
