### ISSUE TITLE
double hyphens `--` breaks HTML validation when commented out

### ISSUE THREAD

**Issue by cweiske** [bem/bem-method#440]
https://en.bem.info/methodology/naming-convention/#alternative-naming-schemes mentions the following in "Harry Roberts' style":

> Boolean modifiers are delimited by double hyphens (--).

When commenting out an HTML area containing such class names, HTML validation breaks because you're not allowed to use double hyphens within comments.

Please add a warning about this. 

----

Reference: https://www.w3.org/TR/2014/REC-html5-20141028/syntax.html#comments

> ... the comment may have text, with the additional restriction that the text must not start with a single ">" (U+003E) character, nor start with a U+002D HYPHEN-MINUS character (-) followed by a ">" (U+003E) character, nor contain two consecutive U+002D HYPHEN-MINUS characters (--), nor end with a U+002D HYPHEN-MINUS character (-). ...

**Comment by tadatuta** [comment]
@cweiske, nice catch, thank you!
