### ISSUE TITLE
Модификатор элемента в project-stub

### ISSUE THREAD

**Issue by rosetau** [bem/bem-method#461]
В туториале "Создаем свой проект на БЭМ" есть раздел "BEMHTML-шаблоны". В разделе есть проверка модификатора элемента: [в этом гисте](https://gist.github.com/innabelaya/8914048#file-gistfile1-txt-L10)
Используется подпредикат для блока, а не для элемента, естественно проверка не срабатывает.

**Comment by godfreyd** [comment]
Спасибо, поправим.

**Comment by tadatuta** [comment]
там должно быть
```js
elemMods: { new: item.new && 'yes' },
```
