### ISSUE TITLE
Опечатка: «Модификаторами» --> «Модификаторы»

### ISSUE THREAD

**Issue by carpogoryanin** [bem/bem-method#474]
https://ru.bem.info/methodology/css/

![image](https://cloud.githubusercontent.com/assets/2052214/17945798/0a129c4c-6a4e-11e6-82b0-0fbff5bfa8bf.png)

**Comment by tadatuta** [comment]
Вроде как текущая формулировка вполне нормальная. Читать как в «молотками забивают гвозди, а модификаторами — задают блокам внешний вид» :)

**Comment by carpogoryanin** [comment]
«Молотками забивают в доски гвозди»
Ок, норм :)
