### ISSUE TITLE
Неправильная ссылка на ENB?

### ISSUE THREAD

**Issue by myshov** [bem/bem-method#503]
В самом первом предложении на странице https://ru.bem.info/toolbox/enb/ ссылка ENB ведет на https://github.com/enb-make. Имхо, она должна вести на каноничный репозитарий https://github.com/enb/enb.

**Comment by tadatuta** [comment]
Спасибо, поправил: https://github.com/bem/bem-method/commit/179d3c815b9c527d64917829e4249106389428a0
